# Generated by Django 4.2.4 on 2023-08-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPagamento', models.CharField(blank=True, max_length=255, null=True, verbose_name='id do pagamento')),
                ('idSessao', models.CharField(blank=True, max_length=255, null=True, verbose_name='id da sessão do pagamento')),
                ('codigoServico', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código do Serviço')),
                ('referencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de referência da GRU')),
                ('competencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Competência (mês e ano)')),
                ('vencimento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vencimento da GRU, se houver')),
                ('cnpjCpf', models.CharField(blank=True, max_length=255, null=True, verbose_name='CPF ou CNPJ')),
                ('nomeContribuinte', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do contribuinte')),
                ('valorPrincipal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Valor Principal')),
                ('valorDescontos', models.CharField(blank=True, max_length=255, null=True, verbose_name='Desconto')),
                ('valorOutrasDeducoes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Outras deduções')),
                ('valorMulta', models.CharField(blank=True, max_length=255, null=True, verbose_name='Multa')),
                ('valorJuros', models.CharField(blank=True, max_length=255, null=True, verbose_name='Juros')),
                ('valorOutrosAcrescimos', models.CharField(blank=True, max_length=255, null=True, verbose_name='Outros Acrescimos')),
                ('modoNavegacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Modo Navegação')),
                ('urlNotificacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL Notificacao')),
                ('dataCriacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Data de criação')),
                ('proximaUrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='Próxima URL')),
                ('tipoPagamentoEscolhido', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de Pagamento')),
                ('nomePSP', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do PSP')),
                ('transacaoPSP', models.CharField(blank=True, max_length=255, null=True, verbose_name='Identificação do pagamento no PSP')),
                ('situacao_codigo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Situação do pagamento')),
                ('situacao_dataHora', models.CharField(blank=True, max_length=255, null=True, verbose_name='Atualização da situação do pgamento')),
            ],
        ),
    ]
