# Generated by Django 4.2.4 on 2023-09-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='refetch',
            field=models.BooleanField(default=False, verbose_name='Bsucar atualizações da API'),
        ),
    ]
